# Description file for samples listing
# The sample names have to be set after "preprocessing workflow" (merging fastq files)
# Exemple:

samples:
    a: preprocessing/mergedFASTQ/a.fastq.gz
    b: preprocessing/mergedFASTQ/b.fastq.gz
