channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake-minimal >=5.24.1
  - jinja2 =2.11
  - networkx =2.5
  - matplotlib =3.3
  - graphviz =2.42
  - bcftools =1.9
  - samtools =1.10
  - bwa =0.7.17
  - pysam =0.15
  - multiqc =1.9
  - fastqc =0.11.9
  - gatk4==4.1.9.0
  - openjdk=8
  - snakemake-wrapper-utils==0.1.3
  - picard==2.23.0
  - optitype==1.3.5
